const keymap = {
    "KeyZ": {name: 'Z', code: 'KeyZ', type: 'note'},
    "KeyX": {name: 'X', code: 'KeyX', type: 'note'},
    "KeyC": {name: 'C', code: 'KeyC', type: 'note'},
    "KeyV": {name: 'V', code: 'KeyV', type: 'note'},
    "KeyB": {name: 'B', code: 'KeyB', type: 'note'},
    "KeyN": {name: 'N', code: 'KeyN', type: 'note'},
    "KeyM": {name: 'M', code: 'KeyM', type: 'note'},
    "Comma": {name: ',', code: 'Comma', type: 'note'},
    "Period": {name: '.', code: 'Period', type: 'note'},
    "Slash": {name: '/', code: 'Slash', type: 'note'},
    "KeyA": {name: 'A', code: 'KeyA', type: 'note'},
    "KeyS": {name: 'S', code: 'KeyS', type: 'note'},
    "KeyD": {name: 'D', code: 'KeyD', type: 'note'},
    "KeyF": {name: 'F', code: 'KeyF', type: 'note'},
    "KeyG": {name: 'G', code: 'KeyG', type: 'note'},
    "KeyH": {name: 'H', code: 'KeyH', type: 'note'},
    "KeyJ": {name: 'J', code: 'KeyJ', type: 'note'},
    "KeyK": {name: 'K', code: 'KeyK', type: 'note'},
    "KeyL": {name: 'L', code: 'KeyL', type: 'note'},
    "Semicolon": {name: ';', code: 'Semicolon', type: 'note'},
    "Quote": {name: '\'', code: 'Quote', type: 'note'},
    "KeyQ": {name: 'Q', code: 'KeyQ', type: 'note'},
    "KeyW": {name: 'W', code: 'KeyW', type: 'note'},
    "KeyE": {name: 'E', code: 'KeyE', type: 'note'},
    "KeyR": {name: 'R', code: 'KeyR', type: 'note'},
    "KeyT": {name: 'T', code: 'KeyT', type: 'note'},
    "KeyY": {name: 'Y', code: 'KeyY', type: 'note'},
    "KeyU": {name: 'U', code: 'KeyU', type: 'note'},
    "KeyI": {name: 'I', code: 'KeyI', type: 'note'},
    "KeyO": {name: 'O', code: 'KeyO', type: 'note'},
    "KeyP": {name: 'P', code: 'KeyP', type: 'note'},
    "BracketLeft": {name: '[', code: 'BracketLeft', type: 'note'},
    "BracketRight": {name: ']', code: 'BracketRight', type: 'note'},
    "Digit1": {name: '1', code: 'Digit1', type: 'note'},
    "Digit2": {name: '2', code: 'Digit2', type: 'note'},
    "Digit3": {name: '3', code: 'Digit3', type: 'note'},
    "Digit4": {name: '4', code: 'Digit4', type: 'note'},
    "Digit5": {name: '5', code: 'Digit5', type: 'note'},
    "Digit6": {name: '6', code: 'Digit6', type: 'note'},
    "Digit7": {name: '7', code: 'Digit7', type: 'note'},
    "Digit8": {name: '8', code: 'Digit8', type: 'note'},
    "Digit9": {name: '9', code: 'Digit9', type: 'note'},
    "Digit0": {name: '0', code: 'Digit0', type: 'note'},
    "Minus": {name: '-', code: 'Minus', type: 'note'},
    "Equal": {name: '=', code: 'Equal', type: 'note'},
}

export default keymap;

